name: Deploy To Production Server

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            echo "✅ Pulling latest code..."
            git pull origin main || true  # only if it's a Git repo

            echo "🔄 Rebuilding Docker container..."
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d --remove-orphans --build

            echo "🚀 Deployment complete"
